version: '3'
services:
  angular-backend-app:
    build: .
    image: angular-backend
    ports:
      - "8090:8090"
    networks: 
      - backend-mysql
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql
  docker-mysql:
    container_name: docker-mysql
    image: mysql
    networks:
      - backend-mysql
    environment:
      MYSQL_DATABASE: angular_poc
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
networks:
  backend-mysql: